Add RfC example for rules service
DEFRA/sroc-service-team pull request #115
Opened 2022-01-13 13:52 UTC by Cruikshanks

We have examples for what to submit when raising an RfC for the Charging Module API (CHA) and the Tactical Charging Module (TCM). What we don't have though is one for the Rules Service (RS).

This change adds one.

2022-01-14 11:02 UTC, Cruikshanks commented
If you wouldn't mind giving it a first pass @StuAA78 then I can merge it and give the link to the wider team. That way it'll be easier for them to review than trying to just look at the diff.

2022-01-14 15:47 UTC, StuAA78 requested changes
One tiny typo to be corrected, otherwise all looks good to me! 😁

2022-01-14 15:47 UTC, StuAA78 commented on rfc/rs.md
> +The following is an example of a completed myIT RfC for the [Rules service](/services/README.md). Unlike the [CHA](/rfc/cha.md) and the [TCM](/rfc/tcm.md) this is based on **Standard Change STDCHG000
Small typo

```suggestion
The following is an example of a completed myIT RfC for the [Rules service](/services/README.md). Unlike the [CHA](/rfc/cha.md) and the [TCM](/rfc/tcm.md) this is based on **Standard Change STDCHG0001214 - Charging Module Rules Service - Ruleset updates - Tactical Charging Module**.
```

2022-01-18 11:35 UTC, StuAA78 approved these changes

2022-01-18 11:36 UTC, merged