Add release process document
DEFRA/sroc-service-team pull request #12
Opened 2020-09-18 14:59 UTC by Cruikshanks

This change adds a document that details the release process for the [charging-module-api](https://github.com/DEFRA/charging-module-api) and the [tactical-charging-module](https://github.com/DEFRA/sroc-tcm-admin).

It's primarily for use by the development team as it details actions they need to take. However, it should be of use to everyone on the team.

2020-09-25 08:51 UTC, StuAA78 requested changes
Spotted a tiny typo in one of the links, all good other than that -- very thorough and clear! 😁

2020-09-25 08:51 UTC, StuAA78 commented on release_process.md
> +We need to update the version held in the app to match our new version. This does mean changing a code file but you'll notice we don't create a PR. This and [updating the CHANGELOG](#update-the-chang
Link is missing the `e` in `changelog`

2020-09-28 10:54 UTC, Cruikshanks commented on release_process.md
> +We need to update the version held in the app to match our new version. This does mean changing a code file but you'll notice we don't create a PR. This and [updating the CHANGELOG](#update-the-chang
🤦

2020-09-28 15:37 UTC, StuAA78 approved these changes
👍

2020-09-28 15:48 UTC, merged